### PR TITLE
Install dependencies and set up project on a pi

### PR DESCRIPTION
**Pull request by cyrilwanner**
It took a bit longer to get opencv working correctly, and it turns out that we can't use poetry on the pi since that ignores piwheels (repository with pre-built binaries for raspberry pi) and tries to build opencv from source which literally takes hours. But we can still use it to generate the dependency list and pass it to pip, so I think this is still fine.

Real stereo will be installed as a system service, meaning it will start automatically on boot and restarts when it crashes (until a certain amount of times).

There are some scripts useful for development which are described in detail in `scripts/README.md`.
Tldr; run `./scripts/pi-run-backend.sh <ip-address>` to deploy & run the backend to a pi and `./scripts/pi-update-frontend.sh <ip-address>` to deploy & build the frontend. I decided that it doesn't make sense to start the frontend dev server on the pi since it is really slow. We can probably still develop the frontend locally on our pc and use the backend from the pi.
When executing the `pi-run-backend.sh`, the system service automatically gets stopped so we can manually run it and attach to the output. But after a reboot, it will be started again.

In `documents/raspberry-setup.md`, all instructions are described to set this project up on a pi. A full installation takes about 15 minutes.

**Please note**, if you test the setup on this branch before it gets merged into the main branch, use the following command for step 5 instead of the one in the document. When it is merged into the main branch, the one from the document should be correct again.

```bash
export PROJECT_BRANCH="feature/raspberry-setup" && curl -sSL https://raw.githubusercontent.com/ItsEcholot/real-stereo-extended/feature/raspberry-setup/scripts/pi-install.sh | bash -
```

### CODE REVIEW

**Comment by ItsEcholot** [comment]
Thanks this looks like a really neat setup 👍 I will try to setup both of my Pis today and report back how it went.

**Review by ItsEcholot — APPROVED** [review]
The scripts worked flawlessly 👍
I have a few questions though. 
1. Am I seeing correctly that Pi are always setup as a slave by default (since there's no option or argument passed to the backend)? Is the idea that the user configures the type in the website that is served when no Wifi connection has been configured?
2. The web app seems to get hosted either way even if the node is a slave. Is that intended?

**Comment by cyrilwanner** [comment]
1. Yes, it is currently intended like this. He can select if he wants to create a new master of it it should act as a slave and then configure the network. This is currently done with the `"type": "unconfigured"` (default) in the config.json. Once the user has selected it, it will change to `"master"` or `"slave"`. Not sure if this is the best user experience, so just tell me if you have a better idea :) The `--master` argument is only intended for development (to force it), for production use, it should be read from the config.json file so we don't have to pass any argument there.
2. Yes, for `"type": "unconfigured"`, the web app will also get served (so the user can configure it). As soon as you change it to `"slave"`, it should no longer be served. While for `"master"`, it will of course still be available.

So until we have implemented the configuration step, it probably makes sense to set one to `"type": "slave"` and the other to `"type": "master"` manually.

**Comment by ItsEcholot** [comment]
1. I think that makes sense 👍
2. Finally figured out what my problem was. We used `tracking` not `slave` in the config.json type. I wondered why it was immediately crashing when I changed it to `slave` 😅

**Comment by cyrilwanner** [comment]
> Finally figured out what my problem was. We used tracking not slave in the config.json type. I wondered why it was immediately crashing when I changed it to slave 😅

Ooooh, I'm sorry 😅 I somehow always had slave in mind, but you are of course right 👍

**Pull request merged**
