### PR TITLE
Spectrum analyzer & improved total volume method from findings

### PR DESCRIPTION
**Pull request by ItsEcholot**
This implements a quick spectrum analyser that uses the data from the FFT. This should us help fine tune the volume detection part even better.

I got the following results (also added to a quick word document in our share):
image

Looking at these graphs (generated by an iPhone 11 Pro Max) we can now understand why our old `getTotalVolume` function didn't work as expected... The frequencies over 11'719hz are almost all at 0 power. Why? Is this a limit of the microphones?
Additionally the range from 0 to ~300hz behave really strange as well... These massive peaks are also present at near silence, at least in my room where I tested this. Again, why?

For the moment I improved the `getTotalVolume` method massively by adding lower & higher frequency boundaries while calculating the average. In my limited testing with white & grey noise this worked pretty well. But it also becomes very obvious that even the slightest changes in the way one is holding the phone or even just positioning their body in relation to the speakers can change the result a lot. Bringing the phone closer to a wall for example increases the measured volume, as more sound waves are reflected from the wall back into the microphone.
We could average this out of course, but we I guess we have to instruct the user to turn around their own axis while measuring so we can do this. Or do you have a better idea?

Then there's the subject of choosing which noise type to use for our test sound. White noise should in theory have equal amounts of power for each frequency band. But that of course is **not** how the speakers reproduce this or how the microphone records this. Then there's grey noise which should provide the same amount of _perceived loudness_ in each frequency band, mimicking the way the human hearing works (louder lows and upper highs). So what is better suited? Looking at the graphs, grey noise behaves more linearly in the upper frequencies while having a weird low-end and vice versa with the white noise. What do you think?

### CODE REVIEW

**Comment by cyrilwanner** [comment]
This is awesome and makes testing it way easier! Thanks!

I also ran some tests and recorded videos with sound which hopefully helps you understand the results. My Phone is a Google Pixel 3a (about 2 years old).
- total silence: https://photos.app.goo.gl/sG63j9HUGN5kpMJH9
- white noise: https://photos.app.goo.gl/jZnJr2L9L6f3vGo39
- gray noise: https://photos.app.goo.gl/78TfiLYca2ovJZkN6
- normal song: https://photos.app.goo.gl/S8zHesNMwHYt5cye8

For the test, I always held my phone with the microphone upside in the middle of the room first. After some seconds, I moved it directly in front of one speaker (when the peaks are visible on the video).

In general, it looks totally different than your results. With a totally silent room, all levels are really just at 0 and the noise is way smaller (although the speakers were at about 90%). And it caps even earlier than for you, at like 7000hz (as you can see with the normal song).

The normal song and the noises were about at the same volume, but in the graph, the noises were almost not existent. At first, I thought that my phone maybe has some kind of noise suppression built in, but in the video, you can still hear it. I then compared it with the other website I've used some weeks ago: https://photos.app.goo.gl/cwPNewcupH24F9A29 (same grey noise as above). In the middle of the room, it is at 76dB, in front of a speaker at 85dB. Those values look legit to me, maybe it makes sense to check how they calculated this value and which frequencies they have used for that?

Regarding the different noises, I feel like watching at your graphs, grey noise would better suit us as the music spectrum is (I think) where it has linear results. But I'm not really sure.

> We could average this out of course, but we I guess we have to instruct the user to turn around their own axis while measuring so we can do this. Or do you have a better idea?

Maybe it makes sense to hold it over your head with the microphone upwards? At least the body doesn't block frequencies then and it is close to where your ears are. But I'm not sure if the recorded volume is correct when the microphone is pointed upwards. I think turning around is not a bad option, as we then have multiple samples from the same position. It takes a bit longer to configure, but that should not be a process that will be done too often.

**Comment by ItsEcholot** [comment]
> The normal song and the noises were about at the same volume, but in the graph, the noises were almost not existent. At first, I thought that my phone maybe has some kind of noise suppression built in, but in the video, you can still hear it.

I actually do think that noise suppression could be an issue here, as when I listen to the normal song sample you uploaded the sound in the video behaves pretty strange (especially noticeable after the 10s mark). Or is this just a recording artefact? Even besides that I'm not sure how else to explain that discrepancy between the noise & music samples when they're played at the same volume.

>I then compared it with the other website I've used some weeks ago: https://photos.app.goo.gl/cwPNewcupH24F9A29 (same grey noise as above). In the middle of the room, it is at 76dB, in front of a speaker at 85dB. Those values look legit to me, maybe it makes sense to check how they calculated this value and which frequencies they have used for that?

That's a good idea. I will try to take a look under the hood and understand how they're doing their volume calculation 👍

> Maybe it makes sense to hold it over your head with the microphone upwards? At least the body doesn't block frequencies then and it is close to where your ears are. But I'm not sure if the recorded volume is correct when the microphone is pointed upwards. I think turning around is not a bad option, as we then have multiple samples from the same position. It takes a bit longer to configure, but that should not be a process that will be done too often.

Holding the phone above your head is also a great idea and seems quicker 👍 Regarding the correct volume I guess we will have to try that when we fixed our volume calculation 😅

**Comment by ItsEcholot** [comment]
Please give the newest version a try. I disabled some audio hardware features that could get in our way and changed the volume calculation algorithm (again 😅). This time using an aWeighted table to better calculate the perceived loudness. For this I split our calculated frequency bands into octaves and applied the weights to that.

**Review by cyrilwanner — APPROVED** [review]
Thank you very much! The recorded values are now in the expected range, so it is definitely an improvement and I think we can work with this 👍 

As you can see in the screenshot, grey noise is now distributed over a large range and even high frequencies are now recorded (capped previously at 7k).



On android, I received the following error when enabling the test mode: `TypeError: Failed to execute 'getUserMedia' on 'MediaDevices': Malformed constraint: Cannot use both optional/mandatory and specific or advanced constraints.`
I tried to fix it (see the last commit) since you probably don't have this error on an iPhone. I believe that it was fixed by removing the mandatory constraints as chrome doesn't need the `goog` prefix anymore. Although I'm not 100% sure if I have understood those constraints correctly, so please check them and also if it still works on an iPhone before merging :)

**Comment by ItsEcholot** [comment]
> On android, I received the following error when enabling the test mode: `TypeError: Failed to execute 'getUserMedia' on 'MediaDevices': Malformed constraint: Cannot use both optional/mandatory and specific or advanced constraints.`
> I tried to fix it (see the last commit) since you probably don't have this error on an iPhone. I believe that it was fixed by removing the mandatory constraints as chrome doesn't need the `goog` prefix anymore. Although I'm not 100% sure if I have understood those constraints correctly, so please check them and also if it still works on an iPhone before merging :)

Yeah I actually thought that could happen 😅 Just thought with JS being JS it probably doesn't hurt to have too many properties and could fix it for some old devices but I guess in this case it was a problem. Thanks for the fix and the review 👍

**Pull request merged**
