### PR TITLE
Implement HoG people detector

### PR DESCRIPTION
**Pull request by cyrilwanner**
This implements the HoG people detector (about the same as last semester). It also already reports back the coordinate to the master, but that one doesn't use it currently. First tests have shown good results and I would say even better than last semester (regarding reliability, not fps).

Please note that it takes a few seconds when turning on the balancing until all models are loaded until the first frame is received. After that, it should be around 1 fps currently. As discussed, optimizations will be done in a later step.
Also, the way the mjpeg stream works, makes the delay look even worse. The frame will only be displayed in the browser when the _next_ frame already arrived. So the delay is doubled and you will always be 2s behind instead of 1s.

I also want to try out other classifiers (primarily the YOLO object detector as that has shown some impressive results), so the implementation was also done in an adapter pattern. Maybe the user can then even select which detector he wants to use, but we'll see if that would make sense.

### CODE REVIEW

**Review by ItsEcholot — APPROVED** [review]
Works perfectly and surprisingly accurate for a first version 👍 I noticed that you didn't convert the frame into grayscale like you did during the calibration. Does the HoG classifier use color data or is there simply no performance to be gained when converting to grayscale?

Additionally I noticed this:
image
Obviously not a problem of this PR but something I thought could develop into a problem when I glued the camera to the chip 😅 Seems like more performance could be possible with better cooling...

**Comment by cyrilwanner** [comment]
> Does the HoG classifier use color data or is there simply no performance to be gained when converting to grayscale?

That's a good question. I just copied the HoG logic from last semester and we didn't convert it to grayscale there. Some results on the internet say that there are minor differences (but don't specify if they are better or not). I'll check it out and compare the results.

> Obviously not a problem of this PR but something I thought could develop into a problem when I glued the camera to the chip 😅 Seems like more performance could be possible with better cooling...

Yes, I also noticed the heat. I started the PI and directly stopped our app, and within 15 minutes, the temperature went from 30° to 50° with literally 0% CPU usage. I think the case could be a problem here as there is no airflow.. And obviously, expensive calculations like image processing increase the temperature even more in a shorter time.

I am actually not sure what the best way would be to improve the situation. As the PI automatically throttles above 80°, it shouldn't go above 85° but that is probably already too hot for your glue 😅 And performance is still impacted. So we probably would have to install a fan, but there is probably not enough room in our case anymore.. Do you have an idea to improve the situation?

**Comment by cyrilwanner** [comment]
So, I tested the HoG detector with a grayscale image and I think the results are slightly better (regarding detection). But interestingly, the performance was not better.
But both (detection quality & performance) could also be because of my small sample size.

I already took advantage of the adapter pattern and created an additional detector so we can easily exchange the grayscale with the non-grayscale version for further tests (and check if the better quality was just imagination 😅 ). For now, the grayscale version is the default one.

**Comment by ItsEcholot** [comment]
> I am actually not sure what the best way would be to improve the situation. As the PI automatically throttles above 80°, it shouldn't go above 85° but that is probably already too hot for your glue 😅 And performance is still impacted. So we probably would have to install a fan, but there is probably not enough room in our case anymore.. Do you have an idea to improve the situation?

I didn't even think of the glue, only about the performance. I used a silicon based double sided tape (like [this](https://www.amazon.com/Double-Adhesive-Sticky-Silicone-Household/dp/B0881PFQ3C) one) so temperature isn't gonna affect it at all (at least in this range).
I think a fan is probably not gonna do as much as a heat spreader would... Since the camera sits on top of the CPU we would have to find a way to move the heat away. Maybe with a thin piece of aluminium / copper between the CPU & camera module that extends outwards into the rest of the case? I'm gonna try to find something suitable to test this theory.

> So, I tested the HoG detector with a grayscale image and I think the results are slightly better (regarding detection). But interestingly, the performance was not better.
But both (detection quality & performance) could also be because of my small sample size.
>
> I already took advantage of the adapter pattern and created an additional detector so we can easily exchange the grayscale with the non-grayscale version for further tests (and check if the better quality was just imagination 😅 ). For now, the grayscale version is the default one.

Ah very nice, thanks a lot 👍

**Comment by ItsEcholot** [comment]
So tried to address our overheating issue by adding a heat spreader in the form of an aluminium plate between the camera and the SoC.

image

This helped a lot in the first ~15minutes but after that the heat couldn't be removed from the case fast enough and the PI overheated again... A fan would definitely be needed but I don't think we have any room for it. So I think we should just try to optimise our code and live with the overheating & throttling.

**Comment by cyrilwanner** [comment]
Thank you for trying this out! Yes, I guess the problem is that the heat can't go out of our case..
We can go forward from this by optimizing the code and maybe add a software throttle (e.g. when nothing has moved over a longer time).
Since this PR looks okay, I'll merge it and we can address this issue and optimizations in further PRs.

**Pull request merged**
