### PR TITLE
Implement camera calibration

### PR DESCRIPTION
**Pull request by cyrilwanner**
This performs camera calibration, meaning it will correct the fisheye image and return a flat image.

A default camera calibration is shipped with this PR. Meaning if the camera used is about the same as mine, it should be sufficient. If it is not, a custom camera calibration can be started to improve the calibration.

To start the custom calibration, open a node in the frontend and click on the "Calibrate Camera" button which is hidden in the dropdown located on the camera stream. The instructions should then be shown before calibration is started. If anything is not clear, please tell me.

I noticed that my two cameras are not exactly the same: one is perfectly centered (regarding the black corners), the other one is a bit off to the right. The default calibration was performed using the centered camera and I noticed that at the corners of the other camera, the image is not flat. So I think it makes sense to run a custom calibration for such cases to improve the image recognition later.

Also, you may notice that the resulting image is cropped so there are no black corners anymore. It turned out that using the copping mode of opencv generates better results. I can show you the difference on telegram if you are interested (don't want to show my complete bedroom on the public internet ;)).

### CODE REVIEW

**Comment by ItsEcholot** [comment]
Oh wow that looks awesome! I will try the calibration process tomorrow 👍 

While trying out the GUI I noticed the camera stream doesn't work the first time / before calibration (shows the camera inactive image). After starting the calibration process it starts working fine though. It continues to work even after I cancelled the calibration and then reloaded the webapp. Not quite sure if that is intended or if I'm doing something wrong.

**Comment by cyrilwanner** [comment]
> While trying out the GUI I noticed the camera stream doesn't work the first time / before calibration (shows the camera inactive image). After starting the calibration process it starts working fine though. It continues to work even after I cancelled the calibration and then reloaded the webapp. Not quite sure if that is intended or if I'm doing something wrong.

It is intended that the camera is only active when there is work to do to save resources when there isn't. And work is balancing or calibration. So, it is normal to get that inactive image and you can turn on the camera by turning on balancing.
But I understand that this can be confusing and also a bit annoying when you have to switch to the overview page to enable/disable it again. I could change it so it also automatically starts the camera when the camera stream is accessed and stops is again when the stream ended. Would you prefer that? I think that could be a good solution.

And that the camera stays active after you have cancelled the calibration looks like a bug 😅

**Comment by ItsEcholot** [comment]
Ah of course 🙈 I totally forgot that Balancing wasn't enabled! I guess this log line kinda confused me too: `[Web API] Starting camera stream`. I think temporarily activating it on the node details page and deactivating it after would be a nice to have feature for sure.

**Review by ItsEcholot — CHANGES_REQUESTED** [review]
The calibration works perfectly 👍 Thanks a lot

Maybe we should add a notice to the calibration text that the calibration pattern needs to be held at the edges of the image for the correct cropping to be applied.

**Comment by cyrilwanner** [comment]
Thank you for the feedback! I added the additional part to the calibration instructions and modified how the camera is started/stopped.

The camera now holds a usage counter and each part that uses the camera (balancing, calibration, stream) can acquire/release the camera. If it is at 0, it will be stopped. With this, I hope that I've covered all possible use-cases for starting and stopping. But it could still be that I forgot something.

**Review by ItsEcholot — APPROVED** [review]
Thank you 👍

**Pull request merged**
